package com.kanion.www.model;

import java.math.BigDecimal;

public class JyhCyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_BATCH_NUMBER
     *
     * @mbggenerated Sun Aug 16 09:02:05 CST 2015
     */
    private String sBatchNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_DEVICE_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sDeviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.N_TIMES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private BigDecimal nTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_BATCH_NUMBER
     *
     * @return the value of KY_JYHTQ_CY.S_BATCH_NUMBER
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsBatchNumber() {
        return sBatchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_BATCH_NUMBER
     *
     * @param sBatchNumber the value for KY_JYHTQ_CY.S_BATCH_NUMBER
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsBatchNumber(String sBatchNumber) {
        this.sBatchNumber = sBatchNumber == null ? null : sBatchNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_DEVICE_CODE
     *
     * @return the value of KY_JYHTQ_CY.S_DEVICE_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsDeviceCode() {
        return sDeviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_DEVICE_CODE
     *
     * @param sDeviceCode the value for KY_JYHTQ_CY.S_DEVICE_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsDeviceCode(String sDeviceCode) {
        this.sDeviceCode = sDeviceCode == null ? null : sDeviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.N_TIMES
     *
     * @return the value of KY_JYHTQ_CY.N_TIMES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public BigDecimal getnTimes() {
        return nTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.N_TIMES
     *
     * @param nTimes the value for KY_JYHTQ_CY.N_TIMES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setnTimes(BigDecimal nTimes) {
        this.nTimes = nTimes;
    }
}