package com.kanion.www.model;

import java.math.BigDecimal;
import java.util.Date;

public class JyhCy extends JyhCyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.N_PROCESS
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private BigDecimal nProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_PROCESS_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sProcessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.N_OPERATION_STEPS
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private BigDecimal nOperationSteps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_DEVICE_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sDeviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sOperationStepsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_PRODUCT_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.TM_BW2_STA
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Date tmBw2Sta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.N_SW2_MIN
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Double nSw2Min;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.TM_HEAT_STOP
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Date tmHeatStop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_ZCG_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sZcgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.TM_CY_STA
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Date tmCySta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.TM_CY_END
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Date tmCyEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.F_YY_QTY
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Double fYyQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.F_YY_TOTAL_QTY
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Double fYyTotalQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_ZLYSJG_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sZlysjgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.F_ZLY_VOL
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Double fZlyVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.F_ZLY_TOTAL_VOL
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Double fZlyTotalVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_OPERATOR
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_CHECKER
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sChecker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_OPERATOR_CLASSES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sOperatorClasses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.S_CHECKER_CLASSES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private String sCheckerClasses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.TM_OPERATOR
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Date tmOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_JYHTQ_CY.TM_CHECKER
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    private Date tmChecker;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.N_PROCESS
     *
     * @return the value of KY_JYHTQ_CY.N_PROCESS
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public BigDecimal getnProcess() {
        return nProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.N_PROCESS
     *
     * @param nProcess the value for KY_JYHTQ_CY.N_PROCESS
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setnProcess(BigDecimal nProcess) {
        this.nProcess = nProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_PROCESS_NAME
     *
     * @return the value of KY_JYHTQ_CY.S_PROCESS_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsProcessName() {
        return sProcessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_PROCESS_NAME
     *
     * @param sProcessName the value for KY_JYHTQ_CY.S_PROCESS_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsProcessName(String sProcessName) {
        this.sProcessName = sProcessName == null ? null : sProcessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.N_OPERATION_STEPS
     *
     * @return the value of KY_JYHTQ_CY.N_OPERATION_STEPS
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public BigDecimal getnOperationSteps() {
        return nOperationSteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.N_OPERATION_STEPS
     *
     * @param nOperationSteps the value for KY_JYHTQ_CY.N_OPERATION_STEPS
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setnOperationSteps(BigDecimal nOperationSteps) {
        this.nOperationSteps = nOperationSteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_DEVICE_NAME
     *
     * @return the value of KY_JYHTQ_CY.S_DEVICE_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsDeviceName() {
        return sDeviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_DEVICE_NAME
     *
     * @param sDeviceName the value for KY_JYHTQ_CY.S_DEVICE_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsDeviceName(String sDeviceName) {
        this.sDeviceName = sDeviceName == null ? null : sDeviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_OPERATION_STEPS_NAME
     *
     * @return the value of KY_JYHTQ_CY.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsOperationStepsName() {
        return sOperationStepsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_OPERATION_STEPS_NAME
     *
     * @param sOperationStepsName the value for KY_JYHTQ_CY.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsOperationStepsName(String sOperationStepsName) {
        this.sOperationStepsName = sOperationStepsName == null ? null : sOperationStepsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_PRODUCT_NAME
     *
     * @return the value of KY_JYHTQ_CY.S_PRODUCT_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsProductName() {
        return sProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_PRODUCT_NAME
     *
     * @param sProductName the value for KY_JYHTQ_CY.S_PRODUCT_NAME
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsProductName(String sProductName) {
        this.sProductName = sProductName == null ? null : sProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.TM_BW2_STA
     *
     * @return the value of KY_JYHTQ_CY.TM_BW2_STA
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Date getTmBw2Sta() {
        return tmBw2Sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.TM_BW2_STA
     *
     * @param tmBw2Sta the value for KY_JYHTQ_CY.TM_BW2_STA
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setTmBw2Sta(Date tmBw2Sta) {
        this.tmBw2Sta = tmBw2Sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.N_SW2_MIN
     *
     * @return the value of KY_JYHTQ_CY.N_SW2_MIN
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Double getnSw2Min() {
        return nSw2Min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.N_SW2_MIN
     *
     * @param nSw2Min the value for KY_JYHTQ_CY.N_SW2_MIN
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setnSw2Min(Double nSw2Min) {
        this.nSw2Min = nSw2Min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.TM_HEAT_STOP
     *
     * @return the value of KY_JYHTQ_CY.TM_HEAT_STOP
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Date getTmHeatStop() {
        return tmHeatStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.TM_HEAT_STOP
     *
     * @param tmHeatStop the value for KY_JYHTQ_CY.TM_HEAT_STOP
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setTmHeatStop(Date tmHeatStop) {
        this.tmHeatStop = tmHeatStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_ZCG_CODE
     *
     * @return the value of KY_JYHTQ_CY.S_ZCG_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsZcgCode() {
        return sZcgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_ZCG_CODE
     *
     * @param sZcgCode the value for KY_JYHTQ_CY.S_ZCG_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsZcgCode(String sZcgCode) {
        this.sZcgCode = sZcgCode == null ? null : sZcgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.TM_CY_STA
     *
     * @return the value of KY_JYHTQ_CY.TM_CY_STA
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Date getTmCySta() {
        return tmCySta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.TM_CY_STA
     *
     * @param tmCySta the value for KY_JYHTQ_CY.TM_CY_STA
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setTmCySta(Date tmCySta) {
        this.tmCySta = tmCySta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.TM_CY_END
     *
     * @return the value of KY_JYHTQ_CY.TM_CY_END
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Date getTmCyEnd() {
        return tmCyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.TM_CY_END
     *
     * @param tmCyEnd the value for KY_JYHTQ_CY.TM_CY_END
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setTmCyEnd(Date tmCyEnd) {
        this.tmCyEnd = tmCyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.F_YY_QTY
     *
     * @return the value of KY_JYHTQ_CY.F_YY_QTY
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Double getfYyQty() {
        return fYyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.F_YY_QTY
     *
     * @param fYyQty the value for KY_JYHTQ_CY.F_YY_QTY
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setfYyQty(Double fYyQty) {
        this.fYyQty = fYyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.F_YY_TOTAL_QTY
     *
     * @return the value of KY_JYHTQ_CY.F_YY_TOTAL_QTY
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Double getfYyTotalQty() {
        return fYyTotalQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.F_YY_TOTAL_QTY
     *
     * @param fYyTotalQty the value for KY_JYHTQ_CY.F_YY_TOTAL_QTY
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setfYyTotalQty(Double fYyTotalQty) {
        this.fYyTotalQty = fYyTotalQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_ZLYSJG_CODE
     *
     * @return the value of KY_JYHTQ_CY.S_ZLYSJG_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsZlysjgCode() {
        return sZlysjgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_ZLYSJG_CODE
     *
     * @param sZlysjgCode the value for KY_JYHTQ_CY.S_ZLYSJG_CODE
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsZlysjgCode(String sZlysjgCode) {
        this.sZlysjgCode = sZlysjgCode == null ? null : sZlysjgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.F_ZLY_VOL
     *
     * @return the value of KY_JYHTQ_CY.F_ZLY_VOL
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Double getfZlyVol() {
        return fZlyVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.F_ZLY_VOL
     *
     * @param fZlyVol the value for KY_JYHTQ_CY.F_ZLY_VOL
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setfZlyVol(Double fZlyVol) {
        this.fZlyVol = fZlyVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.F_ZLY_TOTAL_VOL
     *
     * @return the value of KY_JYHTQ_CY.F_ZLY_TOTAL_VOL
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Double getfZlyTotalVol() {
        return fZlyTotalVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.F_ZLY_TOTAL_VOL
     *
     * @param fZlyTotalVol the value for KY_JYHTQ_CY.F_ZLY_TOTAL_VOL
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setfZlyTotalVol(Double fZlyTotalVol) {
        this.fZlyTotalVol = fZlyTotalVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_OPERATOR
     *
     * @return the value of KY_JYHTQ_CY.S_OPERATOR
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsOperator() {
        return sOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_OPERATOR
     *
     * @param sOperator the value for KY_JYHTQ_CY.S_OPERATOR
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsOperator(String sOperator) {
        this.sOperator = sOperator == null ? null : sOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_CHECKER
     *
     * @return the value of KY_JYHTQ_CY.S_CHECKER
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsChecker() {
        return sChecker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_CHECKER
     *
     * @param sChecker the value for KY_JYHTQ_CY.S_CHECKER
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsChecker(String sChecker) {
        this.sChecker = sChecker == null ? null : sChecker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_OPERATOR_CLASSES
     *
     * @return the value of KY_JYHTQ_CY.S_OPERATOR_CLASSES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsOperatorClasses() {
        return sOperatorClasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_OPERATOR_CLASSES
     *
     * @param sOperatorClasses the value for KY_JYHTQ_CY.S_OPERATOR_CLASSES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsOperatorClasses(String sOperatorClasses) {
        this.sOperatorClasses = sOperatorClasses == null ? null : sOperatorClasses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.S_CHECKER_CLASSES
     *
     * @return the value of KY_JYHTQ_CY.S_CHECKER_CLASSES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public String getsCheckerClasses() {
        return sCheckerClasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.S_CHECKER_CLASSES
     *
     * @param sCheckerClasses the value for KY_JYHTQ_CY.S_CHECKER_CLASSES
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setsCheckerClasses(String sCheckerClasses) {
        this.sCheckerClasses = sCheckerClasses == null ? null : sCheckerClasses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.TM_OPERATOR
     *
     * @return the value of KY_JYHTQ_CY.TM_OPERATOR
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Date getTmOperator() {
        return tmOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.TM_OPERATOR
     *
     * @param tmOperator the value for KY_JYHTQ_CY.TM_OPERATOR
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setTmOperator(Date tmOperator) {
        this.tmOperator = tmOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_JYHTQ_CY.TM_CHECKER
     *
     * @return the value of KY_JYHTQ_CY.TM_CHECKER
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public Date getTmChecker() {
        return tmChecker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_JYHTQ_CY.TM_CHECKER
     *
     * @param tmChecker the value for KY_JYHTQ_CY.TM_CHECKER
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    public void setTmChecker(Date tmChecker) {
        this.tmChecker = tmChecker;
    }
}