package com.kanion.www.model;

import java.util.Date;

public class JyhTqDB {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_GY_DB.S_BATCH_NUMBER
     *
     * @mbggenerated Tue Aug 25 19:49:45 CST 2015
     */
    private String sBatchNumber;

    
    private String sDeviceCode;

    
    private String sDeviceName;

    
    private String sProcessName;

    
    private String sStageName;

    
    private String sProductName;

    
    private String sParaName;

    
    private Double nValue;

    
    private String sUnit;

    
    private Date tmCurt;

    
    public String getsBatchNumber() {
        return sBatchNumber;
    }

    
    public void setsBatchNumber(String sBatchNumber) {
        this.sBatchNumber = sBatchNumber == null ? null : sBatchNumber.trim();
    }

    
    public String getsDeviceCode() {
        return sDeviceCode;
    }

    
    public void setsDeviceCode(String sDeviceCode) {
        this.sDeviceCode = sDeviceCode == null ? null : sDeviceCode.trim();
    }

   
    public String getsDeviceName() {
        return sDeviceName;
    }

    
    public void setsDeviceName(String sDeviceName) {
        this.sDeviceName = sDeviceName == null ? null : sDeviceName.trim();
    }

    
    public String getsProcessName() {
        return sProcessName;
    }

    
    public void setsProcessName(String sProcessName) {
        this.sProcessName = sProcessName == null ? null : sProcessName.trim();
    }

    
    public String getsStageName() {
        return sStageName;
    }

   
    public void setsStageName(String sStageName) {
        this.sStageName = sStageName == null ? null : sStageName.trim();
    }

    
    public String getsProductName() {
        return sProductName;
    }

    
    public void setsProductName(String sProductName) {
        this.sProductName = sProductName == null ? null : sProductName.trim();
    }

    
    public String getsParaName() {
        return sParaName;
    }

    
    public void setsParaName(String sParaName) {
        this.sParaName = sParaName == null ? null : sParaName.trim();
    }

    
    public Double getnValue() {
        return nValue;
    }

   
    public void setnValue(Double nValue) {
        this.nValue = nValue;
    }

    
    public String getsUnit() {
        return sUnit;
    }

    public void setsUnit(String sUnit) {
        this.sUnit = sUnit == null ? null : sUnit.trim();
    }

   
    public Date getTmCurt() {
        return tmCurt;
    }

   
    public void setTmCurt(Date tmCurt) {
        this.tmCurt = tmCurt;
    }
}