package com.kanion.www.model;

import java.math.BigDecimal;

public class MidIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_MID_INDEX.ID
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_MID_INDEX.S_PRODUCT_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    private String sProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_MID_INDEX.S_MIDDLE_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    private String sMiddleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_MID_INDEX.S_PROCESS_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    private String sProcessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_MID_INDEX.N_OPERATION_STEPS
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    private BigDecimal nOperationSteps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_MID_INDEX.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    private String sOperationStepsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_MID_INDEX.S_PARA_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    private String sParaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_MID_INDEX.S_TABLE_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    private String sTableName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_MID_INDEX.ID
     *
     * @return the value of KY_MID_INDEX.ID
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_MID_INDEX.ID
     *
     * @param id the value for KY_MID_INDEX.ID
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_MID_INDEX.S_PRODUCT_NAME
     *
     * @return the value of KY_MID_INDEX.S_PRODUCT_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public String getsProductName() {
        return sProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_MID_INDEX.S_PRODUCT_NAME
     *
     * @param sProductName the value for KY_MID_INDEX.S_PRODUCT_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public void setsProductName(String sProductName) {
        this.sProductName = sProductName == null ? null : sProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_MID_INDEX.S_MIDDLE_NAME
     *
     * @return the value of KY_MID_INDEX.S_MIDDLE_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public String getsMiddleName() {
        return sMiddleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_MID_INDEX.S_MIDDLE_NAME
     *
     * @param sMiddleName the value for KY_MID_INDEX.S_MIDDLE_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public void setsMiddleName(String sMiddleName) {
        this.sMiddleName = sMiddleName == null ? null : sMiddleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_MID_INDEX.S_PROCESS_NAME
     *
     * @return the value of KY_MID_INDEX.S_PROCESS_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public String getsProcessName() {
        return sProcessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_MID_INDEX.S_PROCESS_NAME
     *
     * @param sProcessName the value for KY_MID_INDEX.S_PROCESS_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public void setsProcessName(String sProcessName) {
        this.sProcessName = sProcessName == null ? null : sProcessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_MID_INDEX.N_OPERATION_STEPS
     *
     * @return the value of KY_MID_INDEX.N_OPERATION_STEPS
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public BigDecimal getnOperationSteps() {
        return nOperationSteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_MID_INDEX.N_OPERATION_STEPS
     *
     * @param nOperationSteps the value for KY_MID_INDEX.N_OPERATION_STEPS
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public void setnOperationSteps(BigDecimal nOperationSteps) {
        this.nOperationSteps = nOperationSteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_MID_INDEX.S_OPERATION_STEPS_NAME
     *
     * @return the value of KY_MID_INDEX.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public String getsOperationStepsName() {
        return sOperationStepsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_MID_INDEX.S_OPERATION_STEPS_NAME
     *
     * @param sOperationStepsName the value for KY_MID_INDEX.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public void setsOperationStepsName(String sOperationStepsName) {
        this.sOperationStepsName = sOperationStepsName == null ? null : sOperationStepsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_MID_INDEX.S_PARA_NAME
     *
     * @return the value of KY_MID_INDEX.S_PARA_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public String getsParaName() {
        return sParaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_MID_INDEX.S_PARA_NAME
     *
     * @param sParaName the value for KY_MID_INDEX.S_PARA_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public void setsParaName(String sParaName) {
        this.sParaName = sParaName == null ? null : sParaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_MID_INDEX.S_TABLE_NAME
     *
     * @return the value of KY_MID_INDEX.S_TABLE_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public String getsTableName() {
        return sTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_MID_INDEX.S_TABLE_NAME
     *
     * @param sTableName the value for KY_MID_INDEX.S_TABLE_NAME
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    public void setsTableName(String sTableName) {
        this.sTableName = sTableName == null ? null : sTableName.trim();
    }
}