package com.kanion.www.model;

import java.math.BigDecimal;

public class ParaIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_PRODUCT_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private String sProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_PROCESS_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private BigDecimal sProcessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_PROCESS_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private String sProcessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_STAGE_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private String sStageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.N_OPERATION_STEPS
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private BigDecimal nOperationSteps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private String sOperationStepsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_PARA_USE_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private BigDecimal sParaUseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_PARA_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private String sParaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_TABLE_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private String sTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_PARA_FIELD
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private String sParaField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY_PARA_INDEX.S_GRAPH_TYPE_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    private BigDecimal sGraphTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.ID
     *
     * @return the value of KY_PARA_INDEX.ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.ID
     *
     * @param id the value for KY_PARA_INDEX.ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_PRODUCT_NAME
     *
     * @return the value of KY_PARA_INDEX.S_PRODUCT_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public String getsProductName() {
        return sProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_PRODUCT_NAME
     *
     * @param sProductName the value for KY_PARA_INDEX.S_PRODUCT_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsProductName(String sProductName) {
        this.sProductName = sProductName == null ? null : sProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_PROCESS_ID
     *
     * @return the value of KY_PARA_INDEX.S_PROCESS_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public BigDecimal getsProcessId() {
        return sProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_PROCESS_ID
     *
     * @param sProcessId the value for KY_PARA_INDEX.S_PROCESS_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsProcessId(BigDecimal sProcessId) {
        this.sProcessId = sProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_PROCESS_NAME
     *
     * @return the value of KY_PARA_INDEX.S_PROCESS_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public String getsProcessName() {
        return sProcessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_PROCESS_NAME
     *
     * @param sProcessName the value for KY_PARA_INDEX.S_PROCESS_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsProcessName(String sProcessName) {
        this.sProcessName = sProcessName == null ? null : sProcessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_STAGE_NAME
     *
     * @return the value of KY_PARA_INDEX.S_STAGE_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public String getsStageName() {
        return sStageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_STAGE_NAME
     *
     * @param sStageName the value for KY_PARA_INDEX.S_STAGE_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsStageName(String sStageName) {
        this.sStageName = sStageName == null ? null : sStageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.N_OPERATION_STEPS
     *
     * @return the value of KY_PARA_INDEX.N_OPERATION_STEPS
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public BigDecimal getnOperationSteps() {
        return nOperationSteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.N_OPERATION_STEPS
     *
     * @param nOperationSteps the value for KY_PARA_INDEX.N_OPERATION_STEPS
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setnOperationSteps(BigDecimal nOperationSteps) {
        this.nOperationSteps = nOperationSteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_OPERATION_STEPS_NAME
     *
     * @return the value of KY_PARA_INDEX.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public String getsOperationStepsName() {
        return sOperationStepsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_OPERATION_STEPS_NAME
     *
     * @param sOperationStepsName the value for KY_PARA_INDEX.S_OPERATION_STEPS_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsOperationStepsName(String sOperationStepsName) {
        this.sOperationStepsName = sOperationStepsName == null ? null : sOperationStepsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_PARA_USE_ID
     *
     * @return the value of KY_PARA_INDEX.S_PARA_USE_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public BigDecimal getsParaUseId() {
        return sParaUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_PARA_USE_ID
     *
     * @param sParaUseId the value for KY_PARA_INDEX.S_PARA_USE_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsParaUseId(BigDecimal sParaUseId) {
        this.sParaUseId = sParaUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_PARA_NAME
     *
     * @return the value of KY_PARA_INDEX.S_PARA_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public String getsParaName() {
        return sParaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_PARA_NAME
     *
     * @param sParaName the value for KY_PARA_INDEX.S_PARA_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsParaName(String sParaName) {
        this.sParaName = sParaName == null ? null : sParaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_TABLE_NAME
     *
     * @return the value of KY_PARA_INDEX.S_TABLE_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public String getsTableName() {
        return sTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_TABLE_NAME
     *
     * @param sTableName the value for KY_PARA_INDEX.S_TABLE_NAME
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsTableName(String sTableName) {
        this.sTableName = sTableName == null ? null : sTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_PARA_FIELD
     *
     * @return the value of KY_PARA_INDEX.S_PARA_FIELD
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public String getsParaField() {
        return sParaField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_PARA_FIELD
     *
     * @param sParaField the value for KY_PARA_INDEX.S_PARA_FIELD
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsParaField(String sParaField) {
        this.sParaField = sParaField == null ? null : sParaField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY_PARA_INDEX.S_GRAPH_TYPE_ID
     *
     * @return the value of KY_PARA_INDEX.S_GRAPH_TYPE_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public BigDecimal getsGraphTypeId() {
        return sGraphTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY_PARA_INDEX.S_GRAPH_TYPE_ID
     *
     * @param sGraphTypeId the value for KY_PARA_INDEX.S_GRAPH_TYPE_ID
     *
     * @mbggenerated Sun Aug 16 15:50:31 CST 2015
     */
    public void setsGraphTypeId(BigDecimal sGraphTypeId) {
        this.sGraphTypeId = sGraphTypeId;
    }
}