package com.kanion.www.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.junit.runners.Parameterized.Parameters;

import com.kanion.www.model.JyhCy;
import com.kanion.www.model.JyhCyKey;

public interface JyhCyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_JYHTQ_CY
     *
     * @mbggenerated Sun Aug 16 09:02:06 CST 2015
     */
    int deleteByPrimaryKey(JyhCyKey key);

    
    int insert(JyhCy record);

   
    int insertSelective(JyhCy record);

    
    JyhCy selectByPrimaryKey(JyhCyKey key);
    List<JyhCy> selectByBatchNos(@Param("tableName")String tableName,@Param("minBatchNo")String minBatchNo, @Param("maxBatchNo")String maxBatchNo); 
   
    int updateByPrimaryKeySelective(JyhCy record);

    List selectByBatNoPm(@Param("tableName")String tableName,@Param("minBatchNo")String minBatchNo, @Param("maxBatchNo")String maxBatchNo,
    		@Param("productName")String productName);
    int updateByPrimaryKey(JyhCy record);
}