package com.kanion.www.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.kanion.www.model.JyhTqDB;

public interface JyhTqDBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_GY_DB
     *
     * @mbggenerated Tue Aug 25 19:49:45 CST 2015
     */
    int insert(JyhTqDB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_GY_DB
     *
     * @mbggenerated Tue Aug 25 19:49:45 CST 2015
     */
    int insertSelective(JyhTqDB record);
    List<String> slStage(@Param("processName")String processName);
    List<String> slProcess(@Param("productName")String productName);
    List<Map<String,Object>> slProcessAndBo(@Param("productName")String productName);
    List<Map<String,Object>> slStageAndParam(@Param("processName")String processName);
    List<String> slParam(@Param("stageName")String stageName);
    List<Map<String,Object>> slValueAndUnit(@Param("productName")String productName,
    		@Param("processName")String processName,@Param("stageName")String stageName,
    		@Param("paraName")String paraName,@Param("batchName")String batchName);
    List<String>slDevice(@Param("batchName")String batchName);
}