package com.kanion.www.dao;

import com.kanion.www.model.JyhTqBw;

public interface JyhTqBwMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_GY_DB
     *
     * @mbggenerated Tue Aug 25 19:41:08 CST 2015
     */
    int insert(JyhTqBw record);
    int insertSelective(JyhTqBw record);
}