package com.kanion.www.dao;

import com.kanion.www.model.MidIndex;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MidIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY_MID_INDEX
     *
     * @mbggenerated Sat Aug 15 21:22:07 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal id);
    int insert(MidIndex record);

    int insertSelective(MidIndex record);

    MidIndex selectByPrimaryKey(BigDecimal id);
    String selectByPnameAndMid (@Param("productName")String productName,@Param("midName")String midName);
    List<String> selectMidByPname(@Param("productName")String productName);
    int updateByPrimaryKeySelective(MidIndex record);
    int updateByPrimaryKey(MidIndex record);
    List<String> selectParamByPmMid(@Param("productName")String productName,@Param("midName")String midName);
}